#include<stdio.h>

int main(){
	int num;num=69;
	printf("\\\\:  babaisyou\\babaisyou\n");
	// printf("\\babaisyou\!babaisyou\n");
	printf("\\\":  babaisyou\"babaisyou\n");
	// printf("\\babaisyou\#babaisyou\n");
	// printf("\\babaisyou\$babaisyou\n");
	printf("\\%:  babaisyou\%babaisyou\n",num);
	// printf("\\babaisyou\&babaisyou\n");
	printf("\\\':  babaisyou\'babaisyou\n");
	printf("\\\(:  babaisyou\(babaisyou\n");
	// printf("\\babaisyou\)babaisyou\n");
	// printf("\\babaisyou\*babaisyou\n");
	// printf("\\babaisyou\+babaisyou\n");
	// printf("\\babaisyou\,babaisyou\n");
	// printf("\\babaisyou\-babaisyou\n");
	// printf("\\babaisyou\.babaisyou\n");
	// printf("\\babaisyou\/babaisyou\n");
	printf("\\0:  babaisyou\0babaisyou\n");
	printf("\n");
	printf("\\1:  babaisyou\1babaisyou\n");
	printf("\\2:  babaisyou\2babaisyou\n");
	printf("\\3:  babaisyou\3babaisyou\n");
	printf("\\4:  babaisyou\4babaisyou\n");
	printf("\\5:  babaisyou\5babaisyou\n");
	printf("\\6:  babaisyou\6babaisyou\n");
	printf("\\7:  babaisyou\7babaisyou\n");
	// printf("\\8:  babaisyou\8babaisyou\n");
	// printf("\\9:  babaisyou\9babaisyou\n");
	printf("\\a:  babaisyou\ababaisyou\n");
	printf("\\b:  babaisyou\bbabaisyou\n");
	// printf("\\c:  babaisyou\cbabaisyou\n");
	// printf("\\d:  babaisyou\dbabaisyou\n");
	printf("\\e:  babaisyou\ebabaisyou\n");
	printf("\\f:  babaisyou\fbabaisyou\n");
	// printf("\\g:  babaisyou\gbabaisyou\n");
	// printf("\\h:  babaisyou\hbabaisyou\n");
	// printf("\\i:  babaisyou\ibabaisyou\n");
	// printf("\\j:  babaisyou\jbabaisyou\n");
	// printf("\\k:  babaisyou\kbabaisyou\n");
	// printf("\\l:  babaisyou\lbabaisyou\n");
	// printf("\\m:  babaisyou\mbabaisyou\n");
	printf("\\n:  babaisyou\nbabaisyou\n");
	// printf("\\o:  babaisyou\obabaisyou\n");
	// printf("\\p:  babaisyou\pbabaisyou\n");
	// printf("\\q:  babaisyou\qbabaisyou\n");
	printf("\\r:  babaisyou\rbabaisyou\n");
	// printf("\\s:  babaisyou\sbabaisyou\n");
	printf("\\t:  babaisyou\tbabaisyou\n");
	printf("\\u:  babaisyou\ueabaisyou\n");
	printf("\\v:  babaisyou\vbabaisyou\n");
	// printf("\\w:  babaisyou\wbabaisyou\n");
	printf("\\x:  babaisyou\x49isyou\n");
	// printf("\\y:  babaisyou\ybabaisyou\n");
	// printf("\\z:  babaisyou\zbabaisyou\n");
	return 0;
}
